apiVersion: apps/v1
kind: Deployment
metadata:
  name: polaris-front
  labels:
    app: polaris-front
spec:
  replicas: 1  # Apenas um pod será criado
  selector:
    matchLabels:
      app: polaris-front
  template:
    metadata:
      labels:
        app: polaris-front
    spec:
      containers:
        - name: polarisfront
          image: caiovsk/polarisfront:latest  # Certifique-se de que a imagem está no Docker Hub
          ports:
            - containerPort: 8083  # Porta exposta no contêiner
