name: PolarisV2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.0.x']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: |
        dotnet test --configuration Release --no-restore --collect:"XPlat Code Coverage" --logger "trx;LogFileName=test_results.trx" --results-directory $(System.DefaultWorkingDirectory)/TestResults

    - name: Publish Test Results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: TestResults
        path: $(System.DefaultWorkingDirectory)/TestResults/*.trx

    - name: Report Code Coverage
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:$(System.DefaultWorkingDirectory)/TestResults/**/coverage.cobertura.xml -targetdir:$(System.DefaultWorkingDirectory)/TestResults/CoverageReport -reporttypes:Html
      continue-on-error: true

    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: CodeCoverageReport
        path: $(System.DefaultWorkingDirectory)/TestResults/CoverageReport
