name: PolarisContacts Integration Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-create-service:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger CreateService workflow
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.PAT_TOKEN }}
        script: |
          const { data: workflows } = await github.actions.listRepoWorkflows({
            owner: 'CaioVMoraes',
            repo: 'PolarisContacts.CreateService',
          });
          const workflowId = workflows.workflows.find(w => w.path === 'CreateService.yml').id;

          await github.actions.createWorkflowDispatch({
            owner: 'CaioVMoraes',
            repo: 'PolarisContacts.CreateService',
            workflow_id: workflowId,
            ref: 'main',
          });

  integration-tests:
    needs: trigger-create-service
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.0.x']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install dependencies
      run: dotnet restore

    - name: Run Integration Tests
      run: dotnet test PolarisContacts.IntegrationTests/PolarisContacts.IntegrationTests.csproj --configuration Release --no-restore --logger "trx;LogFileName=IntegrationTestResults/IntegrationTestResults.trx" --collect:"XPlat Code Coverage"

    - name: Publish Integration Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: IntegrationTestResults
        path: '**/IntegrationTestResults/IntegrationTestResults.trx'
