name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.0.x'] # Usando a versão 8.0 do .NET

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Install SQLite
      run: sudo apt-get install -y sqlite3 libsqlite3-dev

    - name: Run All Tests
      run: dotnet test --configuration Release --no-restore --logger "trx;LogFileName=TestResults/TestResults.trx" --collect:"XPlat Code Coverage"

    - name: Publish Test Results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: TestResults
        path: '**/TestResults/TestResults.trx'
