name: PolarisContacts Integration Workflow
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  triggers-services:
    runs-on: ubuntu-latest
 
    steps:
    - name: Trigger CreateService workflow      
      uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
          owner: CaioVMoraes
          repo: PolarisContacts.CreateService
          github_token: ${{ secrets.PAT_TOKEN }}
          workflow_file_name: CreateService.yml
          wait_interval: 0
          wait_workflow: false         
 
    - name: Trigger UpdateService workflow      
      uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
          owner: CaioVMoraes
          repo: PolarisContacts.UpdateService
          github_token: ${{ secrets.PAT_TOKEN }}
          workflow_file_name: UpdateService.yml
          wait_interval: 0
          wait_workflow: false       
 
    - name: Trigger ConsumerService workflow      
      uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
          owner: CaioVMoraes
          repo: PolarisContacts.ConsumerService
          github_token: ${{ secrets.PAT_TOKEN }}
          workflow_file_name: ConsumerService.yml
          wait_interval: 0
          wait_workflow: false
 
    - name: Trigger ReadService workflow      
      uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
          owner: CaioVMoraes
          repo: PolarisContacts.ReadService
          github_token: ${{ secrets.PAT_TOKEN }}
          workflow_file_name: ReadService.yml
          wait_interval: 0
          wait_workflow: false 

 
  integration-tests:
    needs: triggers-services
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        dotnet-version: ['8.0.x']
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
 
    - name: Install dependencies
      run: dotnet restore
 
